[project]
name = "connect-the-current"
version = "0.1.0"
description = "Connect the Current"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "arcade>=3.3.3",
 "pypresence>=4.3.0",
]
